export type ImageSettings = {
    id: string,
    created_at: string,
    good_day_on: boolean,
    high_temp: number,
    high_temp_on: boolean,
    high_uv: number,
    high_uv_on: boolean,
    high_wind: number,
    high_wind_on: boolean,
    low_temp: number,
    low_temp_on: boolean,
    low_visability: number,
    low_visability_on: boolean,
    low_wind: number,
    low_wind_on: boolean,
    rain_chance: number,
    rain_chance_on: boolean,
    snow_chance: number,
    snow_chance_on: boolean,
}