export type HourProp = {
    chance_of_rain: number,
    chance_of_snow: number,
    condition: {
        text: string,
        icon: string,
    },
    feelslike_c: number,
    feelslike_f: number,
    wind_mph: number,
    wind_kph: number,
    temp_c: number,
    temp_f: number,
    time: string,
    time_epoch: number,
    uv: number,
    vis_miles: number,
    vis_km: number,
    will_it_rain: number,
    will_it_snow: number,
    placeholder: boolean,
}