import { HourProp } from "./HourProp"

export type HoursOverview = [
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
    HourProp,
]
